import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#000000',
  },
  container: {
    flex: 1,
    backgroundColor: '#000000',
    alignItems: 'center',
    paddingHorizontal: 24,
  },

  dialSection: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '20%',
    marginBottom: 20,
  },
  dialGlowContainer: {
    width: 280,
    height: 280,
    borderRadius: 140,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#070707',
    borderWidth: 1.5,
    borderColor: '#1c1c1e',
    shadowColor: '#ff2d55',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 22,
    elevation: 12,
  },
  dialInner: {
    width: 280,
    height: 280,
    borderRadius: 140,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tickDot: {
    position: 'absolute',
    width: 2.5,
    height: 2.5,
    borderRadius: 1.25,
    backgroundColor: '#38383a',
  },
  indicatorDot: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ff453a',
    shadowColor: '#ff453a',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 6,
    elevation: 8,
  },
  timeDisplayContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  mainTimeRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'center',
  },
  mainTimeWhite: {
    color: '#ffffff',
    fontSize: 40,
    fontWeight: '600',
    fontVariant: ['tabular-nums'],
    letterSpacing: 0.5,
  },
  mainTimeRed: {
    color: '#ff453a',
    fontSize: 40,
    fontWeight: '600',
    fontVariant: ['tabular-nums'],
    letterSpacing: 0.5,
  },
  subLapTimeText: {
    color: '#8e8e93',
    fontSize: 16,
    fontWeight: '400',
    fontVariant: ['tabular-nums'],
    marginTop: 6,
    letterSpacing: 0.5,
  },
  lapSection: {
    flex: 1,
    width: '100%',
    marginTop: 8,
    marginBottom: 100,
  },
  lapTableHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#222222',
  },
  lapHeaderColLap: {
    color: '#777777',
    fontSize: 14,
    fontWeight: '500',
    width: 60,
    textAlign: 'left',
  },
  lapHeaderColLapTime: {
    color: '#777777',
    fontSize: 14,
    fontWeight: '500',
    flex: 1,
    textAlign: 'center',
  },
  lapHeaderColTotal: {
    color: '#777777',
    fontSize: 14,
    fontWeight: '500',
    width: 90,
    textAlign: 'right',
  },
  lapList: {
    flex: 1,
    width: '100%',
  },
  lapListContent: {
    paddingBottom: 20,
  },
  lapRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#181818',
  },
  lapTextNumber: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '500',
    fontVariant: ['tabular-nums'],
    width: 60,
    textAlign: 'left',
  },
  lapTextSplit: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '400',
    fontVariant: ['tabular-nums'],
    flex: 1,
    textAlign: 'center',
  },
  lapTextTotal: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '400',
    fontVariant: ['tabular-nums'],
    width: 90,
    textAlign: 'right',
  },
  bottomControls: {
    position: 'absolute',
    bottom: 28,
    left: 24,
    right: 24,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  centerOnlyControls: {
    justifyContent: 'center',
  },
  sideButtonSlot: {
    width: 64,
    alignItems: 'center',
    justifyContent: 'center',
  },
});